# Generated by Django 2.1.5 on 2019-03-04 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('published', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=50)),
                ('pagecount', models.IntegerField(blank=True, default=0, null=True)),
                ('img_url', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
                ('users', models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
