# Generated by Django 2.1.5 on 2019-03-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='booklite.Genre'),
        ),
    ]
